import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df= pd.read_excel('football players.xlsx')
print("Dataset loaded successfully!")
print("Shape:",df.shape)
print("Columns:",df.columns)
print(df.head())
df=df.dropna()
df.rename(columns={'goals':'Goals','assists':'Assists','playername':'player_name','Red_cards':'red_cards'},inplace=True)
top_Goals= df.sort_values(by='Goals',ascending=False).head(10)
print("\n Top 10 Players by Goals+Assists:")
print(top_Goals[['player_name','Goals','minutes_played']])
top_minutes= df.sort_values(by='minutes_played',ascending=False).head(10)
print("\n Top 10 Players by minutes_played:")
print(top_minutes[['player_name','minutes_played','Goals']])
df.columns=df.columns.str.strip()
top_reds= df.sort_values(by='red_cards',ascending=False).head(10)
print("\n Players with Most red_cards:")
print(top_reds[['player_name','red_cards','yellow_cards']])
plt.figure(figsize=(10,5))
sns.barplot(x='player_name',y='Goals',data=top_Goals,palette='Greens_r')
plt.title('Top 10 Players by Goals+Assists')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10,5))
sns.barplot(x='player_name',Y='minutes_played',data=top_minutes,palette='Blues')
plt.title('Top 10 Players by minutes_played')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10,5))
sns.barplot(x='player_name',y='red_cards',data=top_Reds,palette='reds')
plt.title('Top 10 Players by red_cards')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
